server.port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo
    username: root
    password: own password
  jpa:
    database-platforms:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000



